# Generated by Django 3.2.7 on 2021-11-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в Телеграме')),
                ('username', models.CharField(blank=True, default='', max_length=50, verbose_name='Имя пользователя в Телеграме')),
                ('first_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=256, verbose_name='Фамилия')),
                ('contact', models.CharField(blank=True, default='', max_length=256, verbose_name='Контакт для связи')),
                ('passport', models.CharField(blank=True, default='', max_length=256, verbose_name='Паспортные данные')),
                ('birthday', models.CharField(blank=True, default='', max_length=256, verbose_name='Дата рождения')),
                ('code', models.ImageField(blank=True, upload_to='QR', verbose_name='картинка')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('period', models.CharField(max_length=256, verbose_name='Период хранения')),
                ('price', models.PositiveIntegerField(verbose_name='Цена заказа')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssbbot.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
            },
        ),
    ]
