# Generated by Django 3.2.7 on 2021-11-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssbbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='storage',
            field=models.CharField(blank=True, max_length=256, verbose_name='Склад'),
        ),
    ]
